### ISSUE TITLE
Shipments with old updated_at but recent completed_at not imported

### ISSUE THREAD

**Issue by ehoch** [DynamoMTL/spree_shipstation#12]
So this one took me months to track down but I figured out why several of our orders were not being imported!

So currently the between scope runs on the shipment's updated_at timestamp. But here's where we were running into issues:

1) Order was created, let's say on 8/23. Shipment was created. User did not complete checkout.
2) User comes back on 8/27 and completes order. Shipment updated_at is still 8/23, but order completed_at/updated_at is 8/27

Hence, shipment will not be imported.

I'm not sure what the best solution is here. Should we patch/hack spree to touch all shipments when an order is completed? Or should we update the scope to be based on shipment updated_at OR order completed_at

Let me know your thoughts. And again, thank you for this wonderful plugin. Been amazing for us these last few months...

**Comment by joshnuss** [comment]
Yo @ehoch

Great catch!

Had this exact issue on my TODO list for a while now - couldn't seems to figure it out.
So huge thank you for sharing, it explains the problem exactly.

The OR/scope seems the least intrusive, just need to make sure that it doesnt slow down the SQL query.

Feel free to submit a PR, or I can get to it later today

Thanks Again,
- Josh

**Comment by ehoch** [comment]
@joshnuss Seems pretty to just scope it then. Let me work on a PR with coverage shortly.

**Comment by joshnuss** [comment]
:+1: 

Also we might need to adjust the LastModified element: https://github.com/DynamoMTL/spree_shipstation/blob/master/app/views/spree/shipstation/export.xml.builder#L34

Should probably be `[order.completed_at, shipment.updated_at].max.strftime...`

**Comment by ehoch** [comment]
@joshnuss Great call. So do you think we should be checking the updated_at or completed_at timestamp for the order in both the scope / xml field?

**Comment by joshnuss** [comment]
@ehoch the OR condition in the Shipment#exportable scope is the most important part

Calling #max in the view might not be needed. Depends on whether ShipStation will pull the new order even if LastModified is outside the requested date range.

**Comment by ehoch** [comment]
@joshnuss Oh I think we definitely want it for both. I have the code written (and spec'd) already. It's ugly since ActiveRecord blows with ORs:

```
    joins(:order).where('(spree_shipments.updated_at > ? AND spree_shipments.updated_at < ?) OR (spree_orders.completed_at > ? AND spree_orders.completed_at < ?)',from, to, from, to)
```

I just am trying to figure out if we want spree_orders.updated_at or spree_orders.completed_at. I'm thinking updated_at in case other aspects change in the order right?

**Comment by joshnuss** [comment]
Agree that checking updated_at instead of completed_at is better, lets do that

sorry bout my typo earlier, I said `Shipment#exportable`, meant to say `Shipment#between`

**Comment by swrobel** [comment]
Wow, awesome. Good catch!
