### ISSUE TITLE
gem not listed on rubygems.org

### ISSUE THREAD

**Issue by jormon** [DynamoMTL/spree_shipstation#16]
It appears that this gem is no longer packaged and listed on rubygems.org?

http://rubygems.org/search?utf8=%E2%9C%93&query=spree_shipstation

**Comment by bryanmtl** [comment]
Hey @joshnuss - is this something you can take care of?

**Comment by joshnuss** [comment]
Hey Bry,

Yeah, I can push them up.

Do we have a DynamoMTL rubygems account? or shall I use mine?

On Wed, May 7, 2014 at 8:02 PM, Bryan Mahoney notifications@github.comwrote:

> Hey @joshnuss https://github.com/joshnuss - is this something you can
> take care of?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DynamoMTL/spree_shipstation/issues/16#issuecomment-42497990
> .

## 

Joshua Nussbaum

**Comment by bryanmtl** [comment]
I don't have one, let's go ahead and use yours.

**Comment by joshnuss** [comment]
All done.

http://rubygems.org/gems/spree_shipstation
