### ISSUE TITLE
Authorize/Capture flow

### ISSUE THREAD

**Issue by swrobel** [DynamoMTL/spree_shipstation#2]
Since I know there's somebody live out there, I'll open this for discussion rather than just forking and heading off in another direction. First off, let me say I really appreciate you saving me the trouble of figuring out how to make spree work w/ the godawful XML api that shipstation has.

So, we're migrating from a Magento store (barf, not my choice, hence we're ditching it) and the ShipStation Magento extension works pretty flawlessly. Here's how the flow goes:
1. Customer places order
2. Card authorized
3. ShipStation picks up order if authorized (shipment would be pending in Spree)
4. Ship the order when we can in ShipStation
5. ShipStation notifies the marketplace
6. Marketplace captures the payment, shipment is marked as shipped

The difference with the way your gem works is you seem to expect the payment to be state paid, or rather for the shipment state to be ready, which happens after payment state is set to paid. I'm kinda rambling here ... any thoughts on the subject?

**Comment by joshnuss** [comment]
Hey Swrobel,

Shouldnt be too-too hard to support capturing the payment post packing. 

Some things would need to be loosened a bit.

1) the `Shipment#exportable` scope should not be hard coded to non-pending shipments 
2) the `ShipmentNotice#update` method should not be hard coded to mark the shipment "shipped". Also, dont think its firing the state machine events, which you will need to hook into to capture the payment.

pull requests very welcome :)

**Comment by swrobel** [comment]
Awesome, I'll get on it!

**Comment by swrobel** [comment]
FYI, I ended up setting auto_capture to true. Made things a lot easier across the board.

**Comment by joshnuss** [comment]
cool. btw i'm changing the code slightly. Will be exporting orders instead of shipments.
hopefully that doesnt effect you?

**Comment by swrobel** [comment]
I was wondering about that. I think it makes more sense that way, although for 2.0 compatibility with split_shipments, Shipments might make more sense in the long-haul.

Also was wondering why you don't just use `@shipment.ship!` in `lib/spree/shipment_notice.rb` since that triggers callbacks, state machine, etc

@neddenriep noticed that line_items weren't being marked as shipped which didn't allow RMA creation, so his fix is here: https://github.com/ScienceInc/spree_shipstation/commit/39753912c4aba1ef9ab8fa9259707855560c21d7

**Comment by joshnuss** [comment]
state machine was acting up for some reason when trying the save the shipment, thanks for the fix!

**Comment by swrobel** [comment]
Think he's sending a PR shortly...

**Comment by joshnuss** [comment]
:+1:
