### ISSUE TITLE
Orders not making it into Shipstation

### ISSUE THREAD

**Issue by swrobel** [DynamoMTL/spree_shipstation#3]
Figured I could open this discussion that @neddenriep and I were just having on IM about orders not making it into Shipstation. It seems that since shipstation sends `start_date` & `end_date` params to the shipstation.xml request, somehow orders get missed, perhaps because their start/end windows miss some span of time or something. I haven't quite figured out what is going on, though I've been digging through logs to try to figure it out. I've found that finding the affected shipment and doing `.touch` on it makes it show up in the next shipstation refresh, but still, this is frustrating to have to be proactive about finding the ones that are missed. Wanted to see if you guys were seeing the same issue, and if you have talked to Shipstation about it?

**Comment by joshnuss** [comment]
what happens when you visit /shipstation.xml your browser using the same parameters as shipstation. does it show the shipment?

**Comment by joshnuss** [comment]
@swrobel we've bumped into similar issues during testing. we've noticed the Shipment#state was not transitioning to "ready" like it should. 

i've opened an issue with spree: https://github.com/spree/spree/issues/3001
in the meantime, you can monkey patch your app to force shipments ready or manually mark them ready thru the admin

**Comment by swrobel** [comment]
Hm, I actually haven't noticed a problem with our shipment states, but then again, we've overrode the state machine so perhaps that's why. I still think it's an issue with ShipStation missing windows of time in its `start_date` and `end_date` ranges, but I haven't seen it happen again since I reported this. I'm still trying to get in touch with someone on the ShipStation API team to get more info on how it works.

**Comment by joshnuss** [comment]
we could always pad the start/end dates, 

but I would assume shipstation is already doing that on their end to account for the variation between different server's clocks.
so if you find an example, let me know and we'll definitely fix it

cheers,
josh

**Comment by joshnuss** [comment]
Fixed by #12
