### ISSUE TITLE
Sending shipments vs orders

### ISSUE THREAD

**Issue by joshnuss** [DynamoMTL/spree_shipstation#4]
@bryanmtl @swrobel  

the confusion with sending shipments is that we send shipstation our shipment# in their order# field. makes it hard on administrators

we can change it to send our order#, but that would mean when we get tracking numbers back we have to assume their is only one shipment on the order. 

that might be ok for now, or do you guys see a better way?

**Comment by bryanmtl** [comment]
I think we're better off sending the shipment number for now, especially with split shipments coming in 2.0. 
Can we set the order# as a reference somewhere or as a custom field?

**Comment by joshnuss** [comment]
Cool.

We actually are currently sending the order# as a custom field.

So no changes needed :D
