### ISSUE TITLE
Virtual Products - how to no include in shipstation.xml

### ISSUE THREAD

**Issue by ehoch** [DynamoMTL/spree_shipstation#8]
Figured I'd mark this as an issue here so others can benefit!

So our store, [Alarm Grid](https://www.alarmgrid.com), has some weird virtual products (our monitoring packages).

Currently I track them using a shipping category (cleverly titled Monitoring) to make sure I don't charge users in our shipping calculator.

But clearly I should not be sending these to shipstation. Any idea on how to easily edit the code to:

1) not include virtual products in mixed physical/virtual product orders
2) not send shipments at all to shipstation that contain all virtual products

**Comment by ehoch** [comment]
Duh, realizing this one is on me. Just going to make sure they don't appear in the shipments. Man, I gotta upgrade to 2.0 for the magic sorting hat and split shipments...

**Comment by mattwbr** [comment]
Hey ehoch,

I am running into this exact same issue! We use Magento and it is sending virtual products to shipstation as well. Did you find a solution?

Thanks!
